const sectors = {
  general:{name:'Genel İşletme',fields:['Raf No','Garanti','Açıklama']},
  market:{name:'Market',fields:['SKT','Gramaj','Tartı Barkodu']},
  clothing:{name:'Giyim / Butik',fields:['Beden','Renk','Sezon']},
  cafe:{name:'Kafe / Restoran',fields:['Masa Bölgesi','Mutfak Yazıcı','Porsiyon']},
  electronics:{name:'Telefoncu / Elektronik',fields:['IMEI','Seri No','Garanti Süresi']},
  autoparts:{name:'Oto Yedek Parça',fields:['OEM Kodu','Araç Uyumu','Şasi / Motor']},
  service:{name:'Servis / Teknik Servis',fields:['Servis Tipi','İşçilik','Cihaz/Plaka']},
  jewelry:{name:'Kuyumcu',fields:['Ayar','Gram','İşçilik']},
  pharmacy:{name:'Eczane / Medikal',fields:['Lot No','SKT','Reçete Notu']},
  petshop:{name:'Pet Shop',fields:['Hayvan Türü','Mama Kg','SKT']}
};
const nav = [
 ['Dashboard','dashboard','🏠'],['Satış','pos','🛒'],['Ürünler','products','📦'],['Stok','stock','📊'],['Barkod / Etiket','barcode','🏷️'],['Cari Hesap','customers','👥'],['Satın Alma','purchase','🧾'],['Tedarikçiler','suppliers','🚚'],['Depo Yönetimi','warehouse','🏬'],['Kasa','cash','💰'],['Personel','staff','👤'],['Raporlar','reports','📈'],['Ayarlar','settings','⚙️']
];
let activePage='dashboard', selectedSector=localStorage.starposSector||'general', cart=[];
let products = JSON.parse(localStorage.starposProducts||'null') || [
 {barcode:'8690637891234',name:'Coca Cola 330 ml',category:'İçecek',brand:'Coca Cola',buy:15,sell:25,stock:125,min:20,unit:'Adet',tax:20,sector:{}},
 {barcode:'8690637890001',name:'Su 0.5 L',category:'İçecek',brand:'Saka',buy:3.5,sell:7.5,stock:250,min:50,unit:'Adet',tax:20,sector:{}},
 {barcode:'8690504012345',name:'Ülker Çikolata',category:'Atıştırmalık',brand:'Ülker',buy:11,sell:18,stock:15,min:20,unit:'Adet',tax:20,sector:{}},
 {barcode:'8690107001030',name:'Çaykur Çay 1 kg',category:'Gıda',brand:'Çaykur',buy:110,sell:149,stock:40,min:50,unit:'Adet',tax:20,sector:{}},
 {barcode:'CLT-001-M-BLK',name:'Basic Tişört',category:'Giyim',brand:'Star',buy:150,sell:299,stock:24,min:10,unit:'Adet',tax:20,sector:{Beden:'M',Renk:'Siyah',Sezon:'Yaz'}},
 {barcode:'TEL-IMEI-001',name:'Telefon Kılıfı',category:'Aksesuar',brand:'Universal',buy:75,sell:149,stock:35,min:8,unit:'Adet',tax:20,sector:{IMEI:'Yok', 'Seri No':'-', 'Garanti Süresi':'6 Ay'}}
];
function money(n){return '₺'+Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2})}
function save(){localStorage.starposProducts=JSON.stringify(products);localStorage.starposSector=selectedSector}
function init(){renderMenu();renderSectors();renderSectorFields();renderAll(); if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
function renderMenu(){document.getElementById('menu').innerHTML=nav.map((n,i)=>`${i===0?'<div class="navGroup">Ana Menü</div>':i===1?'<div class="navGroup">Operasyon</div>':i===10?'<div class="navGroup">Yönetim</div>':''}<button class="navBtn ${n[1]===activePage?'active':''}" onclick="go('${n[1]}')"><span>${n[2]}</span>${n[0]}</button>`).join('')}
function go(page){activePage=page;document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(page).classList.add('active');document.getElementById('pageTitle').textContent=nav.find(n=>n[1]===page)[0];renderMenu();renderAll()}
function renderSectors(){const s=document.getElementById('sectorSelect');s.innerHTML=Object.entries(sectors).map(([k,v])=>`<option value="${k}" ${k===selectedSector?'selected':''}>${v.name}</option>`).join('');s.onchange=e=>{selectedSector=e.target.value;save();renderSectorFields();renderAll()}}
function renderSectorFields(){const box=document.getElementById('sectorFields');box.innerHTML=sectors[selectedSector].fields.map(f=>`<label>${f}<input data-sector-field="${f}" placeholder="${f}" /></label>`).join('')}
function stats(){let sales=cart.reduce((a,c)=>a+c.sell*c.qty,0);return {sales, productCount:products.length, stock:products.reduce((a,p)=>a+Number(p.stock||0),0), low:products.filter(p=>Number(p.stock)<=Number(p.min)).length, profit:products.reduce((a,p)=>a+(p.sell-p.buy)*Math.min(p.stock,10),0)}}
function metric(t,v,i,c,sub=''){return `<div class="card metric"><div><h3>${t}</h3><strong>${v}</strong><p>${sub}</p></div><div class="icon ${c}">${i}</div></div>`}
function renderDashboard(){const s=stats();document.getElementById('dashboard').innerHTML=`<div class="grid4">${metric('Günlük Satış',money(s.sales),'🛒','bgreen','Aktif sepet bazlı')}${metric('Toplam Ürün',s.productCount,'📦','bblue','Tüm sektör ürünleri')}${metric('Toplam Stok',s.stock,'🏬','borange','Depo + raf stokları')}${metric('Kritik Stok',s.low,'⚠️','bpurple','Minimum altı ürün')}</div><div class="layout3" style="margin-top:16px"><div class="card"><h3>Son İşlemler</h3><table class="table"><tr><td>16:45</td><td>Nakit Satış</td><td>${money(269.4)}</td></tr><tr><td>16:30</td><td>Stok Girişi</td><td>+48 Adet</td></tr><tr><td>15:50</td><td>Cari Tahsilat</td><td>${money(750)}</td></tr></table></div><div class="card"><h3>Düşük Stok Uyarıları</h3>${products.filter(p=>p.stock<=p.min).map(p=>`<p class="low">${p.name} — Stok: ${p.stock} / Min: ${p.min}</p>`).join('')||'<p>Uyarı yok</p>'}</div><div class="card"><h3>Sektör Eklentisi</h3><p><b>${sectors[selectedSector].name}</b> aktif.</p><p>Özel alanlar: ${sectors[selectedSector].fields.join(', ')}</p><button class="primary" onclick="go('settings')">Eklentileri Yönet</button></div></div>`}
function renderPOS(){document.getElementById('pos').innerHTML=`<div class="layout"><div><div class="card"><h3>Barkod Oku / Ürün Ekle</h3><div class="toolbar"><input id="barcodeInput" style="flex:1" placeholder="Barkod okutun veya ürün adı yazın..." onkeydown="if(event.key==='Enter') scanBarcode(this.value)"><button class="primary" onclick="scanBarcode(document.getElementById('barcodeInput').value)">Ekle</button><button>📷 Kamera ile Okut</button><button>📡 Bluetooth Okuyucu</button></div><small>Bluetooth/USB okuyucu klavye gibi çalışır. Kamera okutma modülü sonraki entegrasyona hazırdır.</small></div><div class="card" style="margin-top:16px"><h3>Hızlı Ürünler</h3><div class="productGrid">${products.map(p=>`<div class="productCard"><h4>${p.name}</h4><p>${p.barcode}</p><p>Stok: ${p.stock}</p><div class="price">${money(p.sell)}</div><button class="primary" onclick="addCart('${p.barcode}')">+</button></div>`).join('')}</div></div></div><div class="card"><h3>Sepet</h3><div id="cartBox">${cartHtml()}</div></div></div>`}
function cartHtml(){let sub=cart.reduce((a,c)=>a+c.sell*c.qty,0), tax=sub*.2, total=sub+tax;return cart.map(c=>`<div class="cartItem"><div><b>${c.name}</b><p>${c.barcode}</p><button onclick="changeQty('${c.barcode}',-1)">-</button> ${c.qty} <button onclick="changeQty('${c.barcode}',1)">+</button></div><b>${money(c.sell*c.qty)}</b></div>`).join('')+`<div class="cartTotal"><div class="totalLine"><span>Ara Toplam</span><b>${money(sub)}</b></div><div class="totalLine"><span>KDV</span><b>${money(tax)}</b></div><div class="totalLine"><span>Genel Toplam</span><span class="grand">${money(total)}</span></div><div class="toolbar"><button class="success" onclick="completeSale()">Nakit</button><button class="primary" onclick="completeSale()">Kart</button><button onclick="completeSale()">Karma</button></div></div>`}
function scanBarcode(v){if(!v)return;let p=products.find(x=>x.barcode==v || x.name.toLowerCase().includes(v.toLowerCase())); if(p)addCart(p.barcode); else {document.getElementById('pBarcode').value=v;openModal('productModal')} }
function addCart(barcode){let p=products.find(x=>x.barcode==barcode);let c=cart.find(x=>x.barcode==barcode); if(c)c.qty++; else cart.push({...p,qty:1});renderPOS()}
function changeQty(b,d){let c=cart.find(x=>x.barcode==b); if(!c)return;c.qty+=d;if(c.qty<=0)cart=cart.filter(x=>x.barcode!==b);renderPOS()}
function completeSale(){cart.forEach(c=>{let p=products.find(x=>x.barcode==c.barcode); if(p)p.stock=Math.max(0,p.stock-c.qty)});cart=[];save();renderAll();alert('Satış tamamlandı, stoktan düşüldü.')}
function renderProducts(){document.getElementById('products').innerHTML=`<div class="card"><div class="toolbar"><h3 style="margin-right:auto">Ürün Listesi</h3><button class="primary" onclick="openModal('productModal')">+ Yeni Ürün</button><button onclick="exportJson()">Yedek Al</button></div>${productTable()}</div>`}
function productTable(){return `<table class="table"><thead><tr><th>Barkod</th><th>Ürün</th><th>Kategori</th><th>Alış</th><th>Satış</th><th>Stok</th><th>Kritik</th><th>Etiket</th></tr></thead><tbody>${products.map(p=>`<tr><td>${p.barcode}</td><td><b>${p.name}</b><br><span class="pill">${p.brand||'-'}</span></td><td>${p.category}</td><td>${money(p.buy)}</td><td>${money(p.sell)}</td><td class="${p.stock<=p.min?'low':''}">${p.stock} ${p.unit}</td><td>${p.min}</td><td><button onclick="printLabel('${p.barcode}')">Yazdır</button></td></tr>`).join('')}</tbody></table>`}
function renderStock(){document.getElementById('stock').innerHTML=`<div class="card"><h3>Stok Yönetimi</h3><div class="toolbar"><button class="primary">Stok Girişi</button><button>Stok Çıkışı</button><button>Sayım</button><button>Depo Transfer</button></div>${productTable()}</div>`}
function renderBarcode(){document.getElementById('barcode').innerHTML=`<div class="layout3"><div class="card"><h3>Barkod Oluştur</h3><input id="newBarcode" placeholder="Otomatik veya manuel barkod"><button class="primary" onclick="document.getElementById('newBarcode').value='SP'+Date.now().toString().slice(-10)">Oluştur</button></div><div class="card"><h3>Fiyat Etiketi</h3><p>40x30, 58x40, 100x50 etiket şablonları hazır.</p><button class="primary" onclick="printLabel(products[0].barcode)">Örnek Etiket</button></div><div class="card"><h3>Yazıcı Bağlantısı</h3><p>İlk sürüm tarayıcı yazdırma ile çalışır. Zebra/TSC/XPrinter komutları için hazır menü bırakıldı.</p></div></div>`}
function renderGeneric(id,title,items){document.getElementById(id).innerHTML=`<div class="card"><h3>${title}</h3><div class="toolbar"><button class="primary">+ Yeni Kayıt</button><button>Excel Aktar</button><button>Yazdır</button></div><table class="table"><tbody>${items.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join('')}</tbody></table></div>`}
function renderReports(){const s=stats();document.getElementById('reports').innerHTML=`<div class="grid4">${metric('Satış',money(s.sales),'📈','bgreen')}${metric('Tahmini Kâr',money(s.profit),'💹','bblue')}${metric('Ürün',s.productCount,'📦','borange')}${metric('Kritik Stok',s.low,'⚠️','bpurple')}</div><div class="card" style="margin-top:16px"><h3>StarPOS AI Önerileri</h3><p>• Kritik stoktaki ürünler için tedarik siparişi oluşturulmalı.</p><p>• En hızlı satılan ürünlerde minimum stok seviyesi artırılabilir.</p><p>• Sektör seçimine göre rapor filtreleri özelleştirilebilir.</p></div>`}
function renderSettings(){document.getElementById('settings').innerHTML=`<div class="card"><h3>Sektör Eklentileri</h3><p>StarPOS Universal; tek çekirdek yazılım, sektöre göre özel alan ve modüller mantığıyla çalışır.</p><div class="settingsGrid">${Object.entries(sectors).map(([k,v])=>`<div class="moduleBox"><h4>${v.name}</h4><p>${v.fields.join(' • ')}</p><button class="${k===selectedSector?'primary':''}" onclick="selectedSector='${k}';renderSectors();renderSectorFields();save();renderAll()">${k===selectedSector?'Aktif':'Aktifleştir'}</button></div>`).join('')}</div></div>`}
function renderAll(){renderDashboard();renderPOS();renderProducts();renderStock();renderBarcode();renderGeneric('customers','Cari Hesap',[['Ahmet Yılmaz','Müşteri','Borç: ₺750,00'],['ABC Toptan','Tedarikçi','Alacak: ₺2.500,00']]);renderGeneric('purchase','Satın Alma',[['PO-0001','ABC Toptan','Bekliyor'],['PO-0002','Market Tedarik','Tamamlandı']]);renderGeneric('suppliers','Tedarikçiler',[['ABC Toptan','Lefkoşa','Aktif'],['Star Dağıtım','Girne','Aktif']]);renderGeneric('warehouse','Depo Yönetimi',[['Merkez Depo','25.630 Adet','Aktif'],['Şube Depo','3.250 Adet','Aktif']]);renderGeneric('cash','Kasa',[['Kasa Açılış','₺1.000,00','Bugün'],['Nakit Satış','₺269,40','16:45']]);renderGeneric('staff','Personel',[['Yönetici','Tam yetki','Aktif'],['Kasiyer','Satış yetkisi','Aktif']]);renderReports();renderSettings()}
function saveProduct(){let sector={};document.querySelectorAll('[data-sector-field]').forEach(i=>sector[i.dataset.sectorField]=i.value);let p={barcode:pBarcode.value||('SP'+Date.now()),name:pName.value||'Yeni Ürün',category:pCategory.value||'Genel',brand:pBrand.value||'',buy:+pBuy.value||0,sell:+pSell.value||0,stock:+pStock.value||0,min:+pMin.value||0,unit:pUnit.value,tax:+pTax.value||20,sector};let ix=products.findIndex(x=>x.barcode===p.barcode);if(ix>=0)products[ix]=p;else products.push(p);save();closeModal('productModal');renderAll()}
function printLabel(b){let p=products.find(x=>x.barcode===b);document.getElementById('labelPreview').innerHTML=`<h2>${p.name}</h2><div class="barcodeLines">||||||||||||||||</div><p>${p.barcode}</p><h1>${money(p.sell)}</h1>`;openModal('labelModal')}
function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}
function exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(products,null,2)],{type:'application/json'}));a.download='starpos-urun-yedek.json';a.click()}
window.onload=init;
