const menuItems=[['dashboard','🏠','Dashboard'],['pos','🛒','Satış POS'],['products','👕','Ürün Modelleri'],['variants','🎨','Renk/Beden Varyantları'],['stock','📦','Stok & Sayım'],['barcode','🏷️','Barkod / Etiket'],['customers','👥','Müşteri & Sadakat'],['campaigns','🎁','Kampanya'],['purchase','🛍️','Satın Alma'],['suppliers','🚚','Tedarikçiler'],['cash','💰','Kasa'],['staff','👤','Personel'],['reports','📈','Raporlar'],['settings','⚙️','Ayarlar']];
let active='dashboard', cart=[], searchText='';
let models=JSON.parse(localStorage.getItem('starposFashionModels')||'null')||[
 {code:'TSH-001',name:'Oversize T-Shirt',brand:'Star Wear',category:'Üst Giyim',season:'2026 Yaz',collection:'Basic',buy:280,sell:649},
 {code:'JNS-014',name:'Slim Fit Jean',brand:'DenimCo',category:'Alt Giyim',season:'2026 Yaz',collection:'Yeni Sezon',buy:520,sell:1299},
 {code:'DRS-004',name:'Midi Elbise',brand:'Luna',category:'Elbise',season:'2026 Yaz',collection:'Premium',buy:620,sell:1599},
 {code:'SHO-221',name:'Sneaker',brand:'North Star',category:'Ayakkabı',season:'Basic',collection:'Spor',buy:900,sell:1999}
];
let variants=JSON.parse(localStorage.getItem('starposFashionVariants')||'null')||[
 {barcode:'869100000001',model:'TSH-001',color:'Siyah',size:'S',stock:8,min:3,location:'A1'},
 {barcode:'869100000002',model:'TSH-001',color:'Siyah',size:'M',stock:3,min:3,location:'A1'},
 {barcode:'869100000003',model:'TSH-001',color:'Siyah',size:'L',stock:2,min:3,location:'A1'},
 {barcode:'869100000004',model:'TSH-001',color:'Beyaz',size:'M',stock:10,min:3,location:'A2'},
 {barcode:'869100000014',model:'JNS-014',color:'Mavi',size:'38',stock:5,min:2,location:'B1'},
 {barcode:'869100000015',model:'JNS-014',color:'Mavi',size:'40',stock:1,min:2,location:'B1'},
 {barcode:'869100000024',model:'DRS-004',color:'Kırmızı',size:'M',stock:4,min:2,location:'C1'},
 {barcode:'869100000221',model:'SHO-221',color:'Beyaz',size:'42',stock:6,min:2,location:'D1'}
];
function money(n){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(n||0))}
function save(){localStorage.setItem('starposFashionModels',JSON.stringify(models));localStorage.setItem('starposFashionVariants',JSON.stringify(variants))}
function model(code){return models.find(m=>m.code===code)||{name:'Silinmiş Model',sell:0,buy:0,brand:'-',category:'-'}}
function vPrice(v){return Number(v.price||model(v.model).sell||0)}
function init(){renderMenu();fillModelSelect();renderAll();if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function renderMenu(){document.getElementById('menu').innerHTML='<div class="navGroup">Fashion ERP</div>'+menuItems.map(m=>`<button class="navBtn ${active===m[0]?'active':''}" onclick="go('${m[0]}')"><span>${m[1]}</span>${m[2]}</button>`).join('')}
function go(id){active=id;document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');let item=menuItems.find(x=>x[0]===id);pageTitle.textContent=item[2];renderMenu();}
function stats(){let sales=cart.reduce((a,c)=>a+c.price*c.qty,0);return {sales,models:models.length,variants:variants.length,stock:variants.reduce((a,v)=>a+Number(v.stock||0),0),low:variants.filter(v=>Number(v.stock)<=Number(v.min)).length,worth:variants.reduce((a,v)=>a+v.stock*vPrice(v),0)}}
function metric(t,v,i,c,sub=''){return `<div class="card metric"><div><h3>${t}</h3><strong>${v}</strong><p>${sub}</p></div><div class="icon ${c}">${i}</div></div>`}
function variantName(v){let m=model(v.model);return `${m.name} / ${v.color} / ${v.size}`}
function filteredVariants(){let q=searchText.toLowerCase(); if(!q)return variants; return variants.filter(v=>{let m=model(v.model);return [v.barcode,m.name,m.brand,m.category,v.color,v.size,v.location].join(' ').toLowerCase().includes(q)})}
function filterProducts(q){searchText=q;renderVariants();renderProducts();}
function renderDashboard(){let s=stats();dashboard.innerHTML=`<div class="grid4">${metric('Bugünkü Satış',money(s.sales),'🛒','bgreen','Aktif sepet bazlı')}${metric('Model Sayısı',s.models,'👕','bblue','Ürün modeli')}${metric('Varyant',s.variants,'🎨','borange','Renk + beden')}${metric('Kritik Stok',s.low,'⚠️','bpurple','Minimum altı')}</div><div class="layout3" style="margin-top:16px"><div class="card"><h3>Butik Özeti</h3><p>Toplam stok: <b>${s.stock} adet</b></p><p>Stok satış değeri: <b>${money(s.worth)}</b></p><p>Aktif sezon: <b>2026 Yaz</b></p></div><div class="card"><h3>Kritik Stok</h3>${variants.filter(v=>v.stock<=v.min).map(v=>`<p class="low">${variantName(v)} — ${v.stock} adet</p>`).join('')||'<p>Uyarı yok</p>'}</div><div class="card"><h3>StarPOS AI</h3><p>• Siyah L beden ürünleri kritik seviyede.</p><p>• En hızlı dönen kategori: Üst Giyim.</p><p>• Yeni sezonda beden bazlı stok raporu önerilir.</p></div></div>`}
function renderPOS(){pos.innerHTML=`<div class="layout"><div><div class="card"><h3>Satış Ekranı</h3><div class="toolbar"><input id="barcodeInput" class="bigSearch" style="flex:1" placeholder="Barkod okut / ürün adı yaz" onkeydown="if(event.key==='Enter') scan(this.value)"><button class="primary" onclick="scan(barcodeInput.value)">Sepete Ekle</button><button>📷 Kamera</button><button>📡 Bluetooth</button></div><small>USB/Bluetooth okuyucu barkodu yazıp Enter gönderir. Kamera modülü entegrasyona hazırdır.</small></div><div class="card" style="margin-top:16px"><h3>Hızlı Satış</h3><div class="productGrid">${filteredVariants().map(v=>{let m=model(v.model);return `<div class="productCard"><div class="productPhoto">👕</div><h4>${m.name}</h4><p>${m.brand} • ${v.color} • ${v.size}</p><p>Stok: ${v.stock}</p><div class="price">${money(vPrice(v))}</div><button class="primary" onclick="addCart('${v.barcode}')">Ekle</button></div>`}).join('')}</div></div></div><div class="card"><h3>Sepet</h3><div id="cartBox">${cartHtml()}</div></div></div>`}
function cartHtml(){let sub=cart.reduce((a,c)=>a+c.price*c.qty,0),disc=0,total=sub-disc;return cart.map(c=>`<div class="cartItem"><div><b>${c.name}</b><p>${c.color} / ${c.size} / ${c.barcode}</p><button onclick="qty('${c.barcode}',-1)">-</button> ${c.qty} <button onclick="qty('${c.barcode}',1)">+</button></div><b>${money(c.price*c.qty)}</b></div>`).join('')+`<div class="cartTotal"><div class="totalLine"><span>Ara Toplam</span><b>${money(sub)}</b></div><div class="totalLine"><span>İndirim</span><b>${money(disc)}</b></div><div class="totalLine"><span>Genel Toplam</span><span class="grand">${money(total)}</span></div><div class="toolbar"><button class="success" onclick="completeSale()">Nakit</button><button class="primary" onclick="completeSale()">Kart</button><button onclick="completeSale()">Karma</button><button>Askıya Al</button></div></div>`}
function scan(v){if(!v)return;let q=v.toLowerCase();let found=variants.find(x=>x.barcode===v)||variants.find(x=>variantName(x).toLowerCase().includes(q)); if(found)addCart(found.barcode); else{vBarcode.value=v;openModal('variantModal')}}
function addCart(barcode){let v=variants.find(x=>x.barcode===barcode),m=model(v.model),c=cart.find(x=>x.barcode===barcode); if(!v)return;if(c)c.qty++;else cart.push({barcode,name:m.name,color:v.color,size:v.size,price:vPrice(v),qty:1});renderPOS()}
function qty(b,d){let c=cart.find(x=>x.barcode===b);if(!c)return;c.qty+=d;if(c.qty<=0)cart=cart.filter(x=>x.barcode!==b);renderPOS()}
function completeSale(){cart.forEach(c=>{let v=variants.find(x=>x.barcode===c.barcode); if(v)v.stock=Math.max(0,v.stock-c.qty)});cart=[];save();renderAll();alert('Satış tamamlandı. Varyant stokları düşürüldü.')}
function renderProducts(){let rows=models.filter(m=>!searchText||[m.code,m.name,m.brand,m.category,m.season,m.collection].join(' ').toLowerCase().includes(searchText.toLowerCase())).map(m=>{let vs=variants.filter(v=>v.model===m.code);return `<tr><td><b>${m.code}</b></td><td><div class="productPhoto">👗</div></td><td><b>${m.name}</b><br><span class="pill">${m.brand}</span></td><td>${m.category}</td><td>${m.season}</td><td>${m.collection}</td><td>${money(m.buy)}</td><td>${money(m.sell)}</td><td>${vs.reduce((a,v)=>a+Number(v.stock),0)}</td><td>${[...new Set(vs.map(v=>v.color))].map(x=>`<span class="variantTag">${x}</span>`).join('')}</td></tr>`}).join('');products.innerHTML=`<div class="card"><div class="toolbar"><h3 style="margin-right:auto">Ürün Modelleri</h3><button class="primary" onclick="openModal('productModal')">+ Model</button><button onclick="exportJson()">Yedek Al</button></div><table class="table"><thead><tr><th>Model</th><th></th><th>Ürün</th><th>Kategori</th><th>Sezon</th><th>Koleksiyon</th><th>Alış</th><th>Satış</th><th>Stok</th><th>Renkler</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function variantTable(){return `<table class="table"><thead><tr><th>Barkod</th><th>Ürün</th><th>Marka</th><th>Renk</th><th>Beden</th><th>Stok</th><th>Kritik</th><th>Raf</th><th>Fiyat</th><th>Etiket</th></tr></thead><tbody>${filteredVariants().map(v=>{let m=model(v.model);return `<tr><td>${v.barcode}</td><td><b>${m.name}</b><br><span class="pill">${m.category}</span></td><td>${m.brand}</td><td><span class="variantTag">${v.color}</span></td><td><b>${v.size}</b></td><td class="${v.stock<=v.min?'low':''}">${v.stock}</td><td>${v.min}</td><td>${v.location||'-'}</td><td>${money(vPrice(v))}</td><td><button onclick="printLabel('${v.barcode}')">Yazdır</button></td></tr>`}).join('')}</tbody></table>`}
function renderVariants(){variantsSection=document.getElementById('variants');variantsSection.innerHTML=`<div class="card"><div class="toolbar"><h3 style="margin-right:auto">Renk / Beden Varyantları</h3><button class="primary" onclick="openModal('variantModal')">+ Varyant</button></div>${variantTable()}</div>`}
function renderStock(){let colors=[...new Set(variants.map(v=>v.color))], sizes=[...new Set(variants.map(v=>v.size))];stock.innerHTML=`<div class="card"><h3>Stok & Sayım</h3><div class="ribbon"><button class="primary">Stok Girişi</button><button>Stok Çıkışı</button><button>Sayım</button><button>Depo Transfer</button><button>Kritik Stok Raporu</button></div>${variantTable()}</div><div class="card matrix" style="margin-top:16px"><h3>Beden / Renk Matrisi</h3><table class="table"><thead><tr><th>Renk</th>${sizes.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${colors.map(c=>`<tr><td><b>${c}</b></td>${sizes.map(s=>`<td>${variants.filter(v=>v.color===c&&v.size===s).reduce((a,v)=>a+Number(v.stock),0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderBarcode(){barcode.innerHTML=`<div class="layout3"><div class="card"><h3>Barkod Oluştur</h3><input id="newBarcode" placeholder="Otomatik barkod"><button class="primary" onclick="newBarcode.value='869'+Date.now().toString().slice(-10)">Oluştur</button></div><div class="card"><h3>Etiket Şablonu</h3><p>Logo, ürün adı, renk, beden, barkod ve fiyat basımı.</p><button class="primary" onclick="printLabel(variants[0].barcode)">Örnek Etiket</button></div><div class="card"><h3>Yazıcı</h3><p>Zebra / TSC / XPrinter için altyapı menüsü hazır. İlk sürüm tarayıcı yazdırma ile çalışır.</p></div></div>`}
function generic(id,title,rows){document.getElementById(id).innerHTML=`<div class="card"><h3>${title}</h3><div class="toolbar"><button class="primary">+ Yeni</button><button>Yazdır</button><button>Excel</button></div><table class="table"><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`}
function renderReports(){let s=stats();reports.innerHTML=`<div class="grid4">${metric('Stok Değeri',money(s.worth),'💎','bblue')}${metric('Varyant Stok',s.stock,'📦','bgreen')}${metric('Kritik Stok',s.low,'⚠️','borange')}${metric('Sepet Satışı',money(s.sales),'🧾','bpurple')}</div><div class="layout3" style="margin-top:16px"><div class="card"><h3>En Çok Takip Edilecek</h3><p>Renk performansı</p><p>Beden performansı</p><p>Sezon / koleksiyon kârlılığı</p></div><div class="card"><h3>Fashion AI</h3><p>• Siyah ürünlerde L ve XL beden stoğu artırılmalı.</p><p>• Outlet koleksiyonu için kampanya önerilir.</p></div><div class="card"><h3>Raporlar</h3><button>Satış Raporu</button> <button>Stok Raporu</button> <button>Kâr/Zarar</button></div></div>`}
function renderSettings(){settings.innerHTML=`<div class="card"><h3>StarPOS Fashion Ayarları</h3><div class="settingsGrid"><div class="moduleBox"><h4>Beden Setleri</h4><p>XS-XXL, 36-44, ayakkabı numaraları</p></div><div class="moduleBox"><h4>Etiket</h4><p>40x30 / 58x40 / 100x50</p></div><div class="moduleBox"><h4>Yetkiler</h4><p>Admin, kasiyer, depo, muhasebe</p></div><div class="moduleBox"><h4>Bulut</h4><p>Firebase bağlantısı için firebase-config.js dosyasını düzenle.</p></div></div></div>`}
function renderAll(){fillModelSelect();renderDashboard();renderPOS();renderProducts();renderVariants();renderStock();renderBarcode();generic('customers','Müşteri & Sadakat',[['Ayşe Kaya','Puan: 120','Son alışveriş: ₺1.299'],['Zeynep Demir','VIP müşteri','Doğum günü indirimi']]);generic('campaigns','Kampanya Yönetimi',[['2 Al 1 Öde','Üst Giyim','Aktif'],['Sezon Sonu %30','Outlet','Planlandı']]);generic('purchase','Satın Alma',[['PO-FSH-001','Star Wear','Bekliyor'],['PO-FSH-002','DenimCo','Tamamlandı']]);generic('suppliers','Tedarikçiler',[['Star Wear','Tekstil','Aktif'],['DenimCo','Jean tedarikçisi','Aktif']]);generic('cash','Kasa',[['Kasa Açılış','₺2.000','Bugün'],['Kart Satış','₺1.299','16:45']]);generic('staff','Personel',[['Yönetici','Tam yetki','Aktif'],['Kasiyer','Satış + iade','Aktif']]);renderReports();renderSettings()}
function fillModelSelect(){if(!document.getElementById('vModel'))return;vModel.innerHTML=models.map(m=>`<option value="${m.code}">${m.code} — ${m.name}</option>`).join('')}
function saveProductModel(){let p={code:pCode.value||('MDL-'+Date.now().toString().slice(-4)),name:pName.value||'Yeni Model',brand:pBrand.value||'',category:pCategory.value,season:pSeason.value,collection:pCollection.value||'',buy:+pBuy.value||0,sell:+pSell.value||0};let ix=models.findIndex(x=>x.code===p.code);if(ix>=0)models[ix]=p;else models.push(p);save();closeModal('productModal');renderAll()}
function saveVariant(){let v={barcode:vBarcode.value||('869'+Date.now().toString().slice(-10)),model:vModel.value,color:vColor.value||'Standart',size:vSize.value,stock:+vStock.value||0,min:+vMin.value||0,location:vLocation.value||'',price:+vPrice.value||undefined};let ix=variants.findIndex(x=>x.barcode===v.barcode);if(ix>=0)variants[ix]=v;else variants.push(v);save();closeModal('variantModal');renderAll()}
function printLabel(b){let v=variants.find(x=>x.barcode===b),m=model(v.model);labelPreview.innerHTML=`<h2>${m.name}</h2><p>${m.brand} • ${v.color} • ${v.size}</p><div class="barcodeLines">||||||||||||||||</div><p>${v.barcode}</p><h1>${money(vPrice(v))}</h1>`;openModal('labelModal')}
function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}
function exportJson(){const data={models,variants};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='starpos-fashion-yedek.json';a.click()}
window.onload=init;
